# Generated by Django 4.2.4 on 2023-09-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='gameData',
            new_name='game_data',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Your Default Description Here', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(default='gameA', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='selected_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game'),
        ),
    ]
