# Generated by Django 4.2.4 on 2023-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_gamedata_gameplayer_game_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Your Default Description Here', max_length=10000),
        ),
    ]
