# Generated by Django 4.2.4 on 2023-09-18 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
